#!/usr/bin/env python3
"""Apple-style spring → CSS linear() easing.
Usage: spring.py [duration_s] [bounce]   (Apple SwiftUI Spring(duration:bounce:) semantics)
       spring.py --presets                (smooth / snappy / bouncy / gentle / slam)
Prints:  --ease-<name>: linear(...);  --dur-<name>: <settle ms>ms;
bounce 0 = critically damped (no overshoot), 0.15 = subtle, 0.3 = playful, 0.5 = toy.
"""
import math, sys

def spring_linear(duration=0.5, bounce=0.15, n=48):
    # Apple mapping: omega = 2π/duration ; zeta = 1 - bounce  (bounce in [0,1))
    w = 2*math.pi/duration
    z = max(0.0, min(0.999, 1.0 - bounce))
    # settle time: until |x-1| < 0.001
    def x(t):
        if z >= 0.999:  # critically damped
            return 1 - (1 + w*t)*math.exp(-w*t)
        wd = w*math.sqrt(1 - z*z)
        return 1 - math.exp(-z*w*t)*(math.cos(wd*t) + (z*w/wd)*math.sin(wd*t))
    T = duration
    while abs(x(T) - 1) > 0.001 or abs(x(T*1.05) - 1) > 0.001:
        T += 0.01
        if T > 6*duration: break
    pts = [x(T*i/n) for i in range(n+1)]
    pts[-1] = 1.0
    s = ", ".join(("%.3f" % p).rstrip('0').rstrip('.') if p not in (0, 1) else str(int(p)) for p in pts)
    return "linear(%s)" % s, int(round(T*1000/10.0)*10)

PRESETS = {  # name: (duration, bounce) — durations tuned for a 1920×1080 stage, not for UI buttons
    "smooth": (0.6, 0.0),    # settle, no overshoot — text and cards
    "snappy": (0.5, 0.15),   # slight overshoot — cards, pills, discs
    "bouncy": (0.6, 0.3),    # playful — one hero object per deck at most
    "gentle": (1.0, 0.05),   # slow, heavy — full-bleed images, big shapes
    "slam":   (0.45, 0.35),  # stamp / seal landing
}

if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] != "--presets":
        d = float(sys.argv[1]); b = float(sys.argv[2]) if len(sys.argv) > 2 else 0.15
        e, ms = spring_linear(d, b); print("--ease-spring: %s;\n--dur-spring: %dms;" % (e, ms)); sys.exit()
    print("/* Apple-style springs as CSS linear() — generated by scripts/spring.py (Apple Spring(duration:bounce:) mapping). Link this file after your own :root so the linear() values override cubic-bezier fallbacks. Use: transition: transform var(--dur-snappy) var(--ease-snappy). */")
    print("@supports (animation-timing-function: linear(0, 1)) {")
    print("  :root {")
    for k, (d, b) in PRESETS.items():
        e, ms = spring_linear(d, b)
        print("    --ease-%s: %s;\n    --dur-%s: %dms;" % (k, e, k, ms))
    print("  }")
    print("}")
